### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by StarxSky** [FloatTech/voidbot#5]
Could not fetch URL https://pypi.org/simple/websocket-client/: There was a probl
em confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443
): Max retries exceeded with url: /simple/websocket-client/ (Caused by SSLError(
SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)'))) - skippi
ng
ERROR: Could not find a version that satisfies the requirement websocket-client
ERROR: No matching distribution found for websocket-client

**Comment by kanrichan** [comment]
请看README `pip install websocket-client`

**Comment by StarxSky** [comment]
还是报错

**Comment by kanrichan** [comment]
> 还是报错

请尝试更换镜像源

**Comment by StarxSky** [comment]
ok，再试试

**Comment by StarxSky** [comment]
经过更换为清华源的镜像源：
Could not fetch URL https://pypi.tuna.tsinghua.edu.cn/simple/websocket-client/:
There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='py
pi.tuna.tsinghua.edu.cn', port=443): Max retries exceeded with url: /simple/webs
ocket-client/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of p
rotocol (_ssl.c:1125)'))) - skipping
ERROR: Could not find a version that satisfies the requirement websocket-client
ERROR: No matching distribution found for websocket-client

**Comment by StarxSky** [comment]
不好意思哈有点麻烦

**Comment by StarxSky** [comment]
我本来想试试可不可以将Tensorflow训练好的模型加载到bot里

**Comment by kanrichan** [comment]
> 经过更换为清华源的镜像源：
> Could not fetch URL https://pypi.tuna.tsinghua.edu.cn/simple/websocket-client/:
> There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='py
> pi.tuna.tsinghua.edu.cn', port=443): Max retries exceeded with url: /simple/webs
> ocket-client/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of p
> rotocol (_ssl.c:1125)'))) - skipping
> ERROR: Could not find a version that satisfies the requirement websocket-client
> ERROR: No matching distribution found for websocket-client

请检查网络方面的问题

**Comment by StarxSky** [comment]
还是不行诶

**Comment by StarxSky** [comment]
感谢理理，问题已解决经过火绒排查一下发现电脑的host有问题
