### ISSUE TITLE
请教下初始化问题

### ISSUE THREAD

**Issue by Lanyuxxx** [FloatTech/voidbot#6]
请教下大佬，如果我想在voidbot.py刚执行时向群或者个人发送“初始化成功”的文字，我应该在哪个位置编写这个代码

**Comment by kanrichan** [comment]
需要自己进行拓展，可以参考 onebot v11 协议中的 元事件 ，在 meta_event_type 那一行进行改写，自行构造发送的报文

**Comment by Lanyuxxx** [comment]
> 需要自己进行拓展，可以参考 onebot v11 协议中的 元事件 ，在 meta_event_type 那一行进行改写，自行构造发送的报文

刚去看了一下，所以如果要实现的话，就是当 meta_event_type 的值为 lifecycle 的时候去发送的报文吗？我断点看下来在刚开始运行的时候会有一次lifecycle的元事件，但我不清楚是否存在其他的触发条件还会再发生lifecycle的元事件

**Comment by kanrichan** [comment]
那个一般是 websocket 连接成功，服务端那边发过来的，其他时候不会发这个报文，当然你掉线重连也是会发的

**Comment by Lanyuxxx** [comment]
> 那个一般是 websocket 连接成功，服务端那边发过来的，其他时候不会发这个报文，当然你掉线重连也是会发的

好的，谢谢大佬
